### ISSUE TITLE
Postman Collection

### ISSUE THREAD

**Issue by dpeccia** [UTN-FRBA-Mobile/Plantis#3]
Una colleccion de requests en Postman con todas las APIs que queremos consumir y como hacerlo (para que al momento de codear la integracion con las APIs ya sepamos la forma que tienen)

- [x] Identificacion de planta segun una foto
- [x] Informacion general de la planta
- [x] Deteccion de enfermedades de plantas segun una foto
- [x] **[A definir]** Ver si podemos obtener info de cuando regar, fertilizar y transplantar una determinada planta para no tener que setear los reminders a mano

**Comment by mmodugno** [comment]
Queda pendiente el tema a definir. 
**Update:** Busqué apis para saber cuando regar, pero no encontré todavía.
